spring:
  application:
    name: welcome-api
    #register with admin server
  boot:
    admin:
      client:
        url: http://localhost:8888/

server:
  port: 8081

# Manual registration with eureka server
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

#Enable all actuators
management:
  endpoints:
    web:
      exposure:
        include: '*'


