spring:
  application:
    name: greeting-api

  boot:
    admin:
      client:
        url: http://localhost:8888/

#server:
#  port: 8082


management:
  endpoints:
    web:
      exposure:
        include: '*'